platform :ios, '8.0'

use_frameworks!

target 'UUChatTableView' do
    pod 'pop'
    pod 'Masonry'
    pod 'CocoaLumberjack'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'YYText'
    pod 'YYCategories'
    pod 'FMDB'#数据库
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'WZLBadge'#小红点
    pod 'HMSegmentedControl'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'DACircularProgress'
    pod 'QMUIKit'
    pod 'YYKeyboardManager'
    pod 'TZImagePickerController'
    pod 'HMSegmentedControl'
end
